### PR TITLE
Install, Enable and Disable SSLCertificateCommands

### PR DESCRIPTION
**Pull request by solocal-ecommerce**
Missing Install, Enable and Disable SSLCertificateCommands.
Thanks for your work,
Thomas

### CODE REVIEW

**Comment by typhonius** [comment]
Thanks for this, I've just committed the enable/disable task in #83 

If you could rebase this PR on master and include tests for the install task (as #83 did) then I'll get that merged in. You'll be wanting to look at the `SslCertificateCommandTest` class for that, as well as adding in a reference to the right fixture in `AcquiaCliTestCase`.

**Comment by typhonius** [comment]
We should also consider how we manage SSL certificates, keys etc as these may be unwieldy to pass in on the command line. We could potentially pass those in as paths to files too. I'd be keen to solicit information from users to determine what the most appropriate idea would be,

**Comment by typhonius** [comment]
Could of review comments:

* Looks like there's code already committed for ssl:enable / ssl:disable so you can probably remove that and focus only on ssl:create
* Is it likely that users will be able to upload certificates on the command line? They can be really really really long so I wonder if we should point to a certificate file to parse. Thoughts?
* Could you please fix the code sniffer errors below

```
➜  acquia-cli git:(solocal-ecommerce-master) composer cs
> phpcs --standard=PSR12 -n src tests

FILE: ...admalone/repos/acquia-cli/src/Commands/SslCertificateCommand.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 15 | ERROR | [x] Opening brace of a class must be on the line after
    |       |     the definition
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: ...ne/repos/acquia-cli/tests/Commands/SslCertificateCommandTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 81 | ERROR | [x] Expected 1 newline at end of file; 0 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 543ms; Memory: 10MB

Script phpcs --standard=PSR12 -n src tests handling the cs event returned with error code 2
```

**Comment by solocal-ecommerce** [comment]
Hi,
- code sniffer errors have been fixed
- That was easier for me to pass certificates as env variables, but you're right, it will be more generic to pass them using file path. I have refactored it and should now be ok.

**Comment by typhonius** [comment]
Thanks for your work on this @solocal-ecommerce - I've made the changes I recommended in #119 and committed it to master. It will be part of the next tagged release which can be downloaded with the `self:update` command if you are using the phar Cli tool.

**Pull request closed without merging**
